# Generated by Django 5.0.8 on 2024-09-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registers_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registers',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registers',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='registers',
            name='phone',
        ),
    ]
