# Generated by Django 5.0.8 on 2024-09-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_grievance_delete_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(max_length=100)),
                ('ctype', models.CharField(max_length=100)),
                ('cdescription', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Grievance',
        ),
    ]
