# Generated by Django 5.0.8 on 2024-09-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_grievance_delete_complaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='title',
            new_name='complaint_title',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='user',
        ),
        migrations.AlterField(
            model_name='grievance',
            name='grievance_type',
            field=models.CharField(max_length=100),
        ),
    ]
