# Generated by Django 5.0.8 on 2024-09-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_title_grievance_complaint_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grievance',
        ),
    ]
