# Generated by Django 5.0.8 on 2024-09-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_grievance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=255)),
                ('type_of_grievance', models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('others', 'Others')], max_length=50)),
                ('complaint_description', models.TextField()),
            ],
        ),
    ]
