# Generated by Django 5.0.8 on 2024-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
