# Generated by Django 5.0.8 on 2024-09-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='resolution',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.grievance'),
        ),
    ]
