# Generated by Django 5.0.8 on 2024-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_resolution_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackforms',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
    ]
