# Generated by Django 5.0.8 on 2024-10-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_feedbackforms_resolution_delete_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
