# Generated by Django 5.0.8 on 2024-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_grievance_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='department',
            field=models.CharField(default='mca', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grievance',
            name='name',
            field=models.CharField(default='mca', max_length=255),
            preserve_default=False,
        ),
    ]
