# Generated by Django 5.0.8 on 2024-10-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_grievance_department_grievance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_appeal', models.CharField(choices=[('administrative', 'Administrative'), ('academic', 'Academic'), ('student_support', 'Student Support'), ('others', 'Others')], max_length=50)),
                ('appeal_details', models.TextField()),
                ('proposed_action', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='appeal_docs/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
        migrations.AlterField(
            model_name='grievance',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
