# Generated by Django 5.0.8 on 2024-10-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_appeal_alter_grievance_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='appeal_details',
            new_name='details_of_appeal',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='nature_of_appeal',
            field=models.CharField(choices=[('administrative', 'Administrative'), ('academic', 'Academic'), ('student_support', 'Student Support'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='appeals/signatures/'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='appeals/documents/'),
        ),
    ]
